---
title: "PQR'S"
author: "Luis Barrios"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE, 
	cache=TRUE
)
```

```{r data_packages, message=FALSE, warning=FALSE, include=FALSE}
library(readr)
library(readxl)
library(ggplot2)
library(tidyr)
library(dplyr)
library(kableExtra)
library(lubridate)
library(forcats)
library(stringr)
library(gganimate)
library(plotly)
```

```{r data_transformation, message=FALSE, warning=FALSE, include=FALSE}

tickets<-read_xls("tickets2.xls",skip = 2)
# como las fechas estan como carácteres y no date lo convertimos 
tickets$`Created at`<-parse_datetime(tickets$`Created at`)
tickets$`Updated at`<-parse_datetime(tickets$`Updated at`)
tickets$`Closed at`<-parse_datetime(tickets$`Closed at`)
tickets<-tickets %>% mutate(mes=month(`Created at`))
tickets<-tickets %>% filter(mes!="")
```

# Preguntas

1.  ¿Cual es el tiempo promedio por PQR's respecto al área comercial?

2.  ¿Cuales son los PQR's mas frecuentes?

# Conclusiones

1.  

# Cantidad por tipor de PQR

```{r data wrangling}
ticket_comercial<-tickets %>% filter(Title %in% c("0001- Devolución de saldos por mayor valor pagado",
                                                  "0002 - Devolución de saldo de seguro",
                                                  "0003 - Inconsistencia con el pago de florines"  ,
                                                  "0004 - Certificación de consejero"   ,
                                                  "0006 - Certificación declaración de renta" ,
                                                  "0007- Estado de cuenta" ,
                                                  "0007-Estado de cuenta"  ,
                                                  "0008 - Solicitud de Paz y Salvo" ,
                                                  "0009 - Derecho de petición" ,
                                                  "0013 - Reintegro Consejero/Nombramiento Líder" ,
                                                  "0014 - Retiro Consejero/Líder"     ,
                                                  "0015 - Quitar y adicionar crédito de un corte",
                                                  "0016 - Revertir crédito",
                                                  "0017 - Mi Aflore - Consejero",
                                                  "0018 - Mi Aflore - Cliente",
                                                  "0019 - Llenada por Consejero",
                                                  "0020 - Llenada por Cliente",
                                                  "0022 - Falla en el proceso de desembolso Digital",
                                                  "0025 - Cancelación póliza",
                                                  "0027 - Problemas PBX",
                                                  "0054 - Problemas o cambios expansión geográfica",
                                                  "0057  - Problemas ARK o base de datos" ,
                                                  "0057 - Problemas ARK o base de datos",
                                                  "0059 - Corregir Abono negativo a capital",
                                                  "0060 - Pago duplicado"  ))
```

```{r cantidad ,fig.width=10,fig.height=14}
ticket_comercial %>% count(mes,Title) %>% ggplot(aes(x=reorder(Title,n),y=n,fill=factor(mes,levels=c("4","3","2","1")),label=n))+geom_bar(stat = "identity",position = "dodge2")+coord_flip()+labs(x="",y="conteo")+guides(fill=guide_legend(title="mes"))+geom_text(position = position_dodge(width = 0.9))
```

```{r tabla321}
ticket_comercial %>% count(mes,Title) %>% arrange(Title,mes) %>% kbl() %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

# Horas promedio por pqr por mes (gráfico)

```{r plot4,fig.width=10,fig.height=14}


ticket_comercial %>% group_by(Title,mes) %>% summarise(dif_updated_closed=median((`Updated at`- `Created at`)/3600)) %>% arrange(-dif_updated_closed) %>% ggplot(aes(x=reorder(Title,dif_updated_closed),y=dif_updated_closed,fill=factor(mes,levels=c("4","3","2","1")),label=round(dif_updated_closed,digit=1)))+geom_bar(stat = "identity",position = "dodge")+coord_flip()+guides(fill=guide_legend(title="mes"))+labs(x="",y="horas promedio",title = "Horas promedio de resolución por tipo de ticket")+geom_text(position = position_dodge(width = 0.9))

```

# Horas por PQR por mes (tabla)

```{r tabla}
ticket_comercial %>% group_by(mes,Title) %>% summarise(dif_updated_closed= median((`Updated at`- `Created at`)/3600)) %>% arrange(Title,mes) %>% kbl() %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```
